import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';
import apiSidebar from './docs/api/sidebar';

const sidebars: SidebarsConfig = {
  // Main documentation sidebar
  tutorialSidebar: [
    'user-guide',
    'user-usage-flow',
    'api-keys-usage',
  ],

  // API Reference sidebar (generated by docusaurus-plugin-openapi-docs)
  apiSidebar,
};

export default sidebars;
